// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.17.3
// source: simRegistration.proto

package registration

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CustomerDetails struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CustId                 int32                       `protobuf:"varint,1,opt,name=custId,proto3" json:"custId,omitempty"`
	CustName               string                      `protobuf:"bytes,2,opt,name=custName,proto3" json:"custName,omitempty"`
	Email                  string                      `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	AlternateContactNumber string                      `protobuf:"bytes,4,opt,name=alternateContactNumber,proto3" json:"alternateContactNumber,omitempty"`
	AadharNumber           int64                       `protobuf:"varint,5,opt,name=aadharNumber,proto3" json:"aadharNumber,omitempty"`
	Addresses              []*CustomerDetails_Addrress `protobuf:"bytes,6,rep,name=addresses,proto3" json:"addresses,omitempty"`
}

func (x *CustomerDetails) Reset() {
	*x = CustomerDetails{}
	if protoimpl.UnsafeEnabled {
		mi := &file_simRegistration_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CustomerDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CustomerDetails) ProtoMessage() {}

func (x *CustomerDetails) ProtoReflect() protoreflect.Message {
	mi := &file_simRegistration_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CustomerDetails.ProtoReflect.Descriptor instead.
func (*CustomerDetails) Descriptor() ([]byte, []int) {
	return file_simRegistration_proto_rawDescGZIP(), []int{0}
}

func (x *CustomerDetails) GetCustId() int32 {
	if x != nil {
		return x.CustId
	}
	return 0
}

func (x *CustomerDetails) GetCustName() string {
	if x != nil {
		return x.CustName
	}
	return ""
}

func (x *CustomerDetails) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *CustomerDetails) GetAlternateContactNumber() string {
	if x != nil {
		return x.AlternateContactNumber
	}
	return ""
}

func (x *CustomerDetails) GetAadharNumber() int64 {
	if x != nil {
		return x.AadharNumber
	}
	return 0
}

func (x *CustomerDetails) GetAddresses() []*CustomerDetails_Addrress {
	if x != nil {
		return x.Addresses
	}
	return nil
}

type CreateResponseMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CustId     int32  `protobuf:"varint,1,opt,name=custId,proto3" json:"custId,omitempty"`
	SuccessMsg string `protobuf:"bytes,2,opt,name=successMsg,proto3" json:"successMsg,omitempty"`
}

func (x *CreateResponseMessage) Reset() {
	*x = CreateResponseMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_simRegistration_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateResponseMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateResponseMessage) ProtoMessage() {}

func (x *CreateResponseMessage) ProtoReflect() protoreflect.Message {
	mi := &file_simRegistration_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateResponseMessage.ProtoReflect.Descriptor instead.
func (*CreateResponseMessage) Descriptor() ([]byte, []int) {
	return file_simRegistration_proto_rawDescGZIP(), []int{1}
}

func (x *CreateResponseMessage) GetCustId() int32 {
	if x != nil {
		return x.CustId
	}
	return 0
}

func (x *CreateResponseMessage) GetSuccessMsg() string {
	if x != nil {
		return x.SuccessMsg
	}
	return ""
}

type CustomerDetails_Addrress struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HouseNumber string `protobuf:"bytes,1,opt,name=houseNumber,proto3" json:"houseNumber,omitempty"`
	Street      string `protobuf:"bytes,2,opt,name=street,proto3" json:"street,omitempty"`
	City        string `protobuf:"bytes,3,opt,name=city,proto3" json:"city,omitempty"`
	State       string `protobuf:"bytes,4,opt,name=state,proto3" json:"state,omitempty"`
	Zip         int32  `protobuf:"varint,5,opt,name=zip,proto3" json:"zip,omitempty"`
}

func (x *CustomerDetails_Addrress) Reset() {
	*x = CustomerDetails_Addrress{}
	if protoimpl.UnsafeEnabled {
		mi := &file_simRegistration_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CustomerDetails_Addrress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CustomerDetails_Addrress) ProtoMessage() {}

func (x *CustomerDetails_Addrress) ProtoReflect() protoreflect.Message {
	mi := &file_simRegistration_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CustomerDetails_Addrress.ProtoReflect.Descriptor instead.
func (*CustomerDetails_Addrress) Descriptor() ([]byte, []int) {
	return file_simRegistration_proto_rawDescGZIP(), []int{0, 0}
}

func (x *CustomerDetails_Addrress) GetHouseNumber() string {
	if x != nil {
		return x.HouseNumber
	}
	return ""
}

func (x *CustomerDetails_Addrress) GetStreet() string {
	if x != nil {
		return x.Street
	}
	return ""
}

func (x *CustomerDetails_Addrress) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *CustomerDetails_Addrress) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *CustomerDetails_Addrress) GetZip() int32 {
	if x != nil {
		return x.Zip
	}
	return 0
}

var File_simRegistration_proto protoreflect.FileDescriptor

var file_simRegistration_proto_rawDesc = []byte{
	0x0a, 0x15, 0x73, 0x69, 0x6d, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0f, 0x73, 0x69, 0x6d, 0x52, 0x65, 0x67, 0x69,
	0x73, 0x74, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x83, 0x03, 0x0a, 0x0f, 0x43, 0x75, 0x73,
	0x74, 0x6f, 0x6d, 0x65, 0x72, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x12, 0x16, 0x0a, 0x06,
	0x63, 0x75, 0x73, 0x74, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x63, 0x75,
	0x73, 0x74, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x75, 0x73, 0x74, 0x4e, 0x61, 0x6d, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x75, 0x73, 0x74, 0x4e, 0x61, 0x6d, 0x65,
	0x12, 0x14, 0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x36, 0x0a, 0x16, 0x61, 0x6c, 0x74, 0x65, 0x72, 0x6e,
	0x61, 0x74, 0x65, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x63, 0x74, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x16, 0x61, 0x6c, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x74,
	0x65, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x63, 0x74, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x22,
	0x0a, 0x0c, 0x61, 0x61, 0x64, 0x68, 0x61, 0x72, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x0c, 0x61, 0x61, 0x64, 0x68, 0x61, 0x72, 0x4e, 0x75, 0x6d, 0x62,
	0x65, 0x72, 0x12, 0x47, 0x0a, 0x09, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x65, 0x73, 0x18,
	0x06, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x29, 0x2e, 0x73, 0x69, 0x6d, 0x52, 0x65, 0x67, 0x69, 0x73,
	0x74, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72,
	0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x2e, 0x41, 0x64, 0x64, 0x72, 0x72, 0x65, 0x73, 0x73,
	0x52, 0x09, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x65, 0x73, 0x1a, 0x80, 0x01, 0x0a, 0x08,
	0x41, 0x64, 0x64, 0x72, 0x72, 0x65, 0x73, 0x73, 0x12, 0x20, 0x0a, 0x0b, 0x68, 0x6f, 0x75, 0x73,
	0x65, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x68,
	0x6f, 0x75, 0x73, 0x65, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74,
	0x72, 0x65, 0x65, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x72, 0x65,
	0x65, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x69, 0x74, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x63, 0x69, 0x74, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x12, 0x10, 0x0a, 0x03,
	0x7a, 0x69, 0x70, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x7a, 0x69, 0x70, 0x22, 0x4f,
	0x0a, 0x15, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x63, 0x75, 0x73, 0x74, 0x49,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x63, 0x75, 0x73, 0x74, 0x49, 0x64, 0x12,
	0x1e, 0x0a, 0x0a, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x4d, 0x73, 0x67, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0a, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x4d, 0x73, 0x67, 0x32,
	0x71, 0x0a, 0x0f, 0x53, 0x69, 0x6d, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x12, 0x5e, 0x0a, 0x10, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x43, 0x75,
	0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x12, 0x20, 0x2e, 0x73, 0x69, 0x6d, 0x52, 0x65, 0x67, 0x69,
	0x73, 0x74, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65,
	0x72, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x1a, 0x26, 0x2e, 0x73, 0x69, 0x6d, 0x52, 0x65,
	0x67, 0x69, 0x73, 0x74, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x22, 0x00, 0x42, 0x10, 0x5a, 0x0e, 0x2e, 0x2f, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_simRegistration_proto_rawDescOnce sync.Once
	file_simRegistration_proto_rawDescData = file_simRegistration_proto_rawDesc
)

func file_simRegistration_proto_rawDescGZIP() []byte {
	file_simRegistration_proto_rawDescOnce.Do(func() {
		file_simRegistration_proto_rawDescData = protoimpl.X.CompressGZIP(file_simRegistration_proto_rawDescData)
	})
	return file_simRegistration_proto_rawDescData
}

var file_simRegistration_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_simRegistration_proto_goTypes = []interface{}{
	(*CustomerDetails)(nil),          // 0: simRegistration.CustomerDetails
	(*CreateResponseMessage)(nil),    // 1: simRegistration.CreateResponseMessage
	(*CustomerDetails_Addrress)(nil), // 2: simRegistration.CustomerDetails.Addrress
}
var file_simRegistration_proto_depIdxs = []int32{
	2, // 0: simRegistration.CustomerDetails.addresses:type_name -> simRegistration.CustomerDetails.Addrress
	0, // 1: simRegistration.SimRegistration.RegisterCustomer:input_type -> simRegistration.CustomerDetails
	1, // 2: simRegistration.SimRegistration.RegisterCustomer:output_type -> simRegistration.CreateResponseMessage
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_simRegistration_proto_init() }
func file_simRegistration_proto_init() {
	if File_simRegistration_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_simRegistration_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CustomerDetails); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_simRegistration_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateResponseMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_simRegistration_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CustomerDetails_Addrress); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_simRegistration_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_simRegistration_proto_goTypes,
		DependencyIndexes: file_simRegistration_proto_depIdxs,
		MessageInfos:      file_simRegistration_proto_msgTypes,
	}.Build()
	File_simRegistration_proto = out.File
	file_simRegistration_proto_rawDesc = nil
	file_simRegistration_proto_goTypes = nil
	file_simRegistration_proto_depIdxs = nil
}
